### PR TITLE
Problem: macOS runners on GH tend to be slow or expensive

### PR DESCRIPTION
**Pull request by yrashk**
I am seeing some hang.

Solution: try FlyCI

### CODE REVIEW

**Comment by kgantchev** [comment]
@yrashk 
Thanks for switching to [FlyCI](https://flyci.net)! As one of the co-founders of FlyCI, I'm super happy to have you on board. 

Quick question: how did you hear about us?

**Comment by yrashk** [comment]
Saw somewhere on LinkedIn, decided to give it a try.

**Comment by kgantchev** [comment]
> Saw somewhere on LinkedIn, decided to give it a try.

Awesome!

**Comment by yrashk** [comment]
Already done on master

**Comment by radeva** [comment]
Hi @yrashk ,

My name is Veselina and I'm a PM at FlyCI. We're creating a case study around the usage of FlyCI in this repo. In relation to that, I'm wondering if you could share your experience with the product so far?

Thanks!

**Comment by yrashk** [comment]
> Hi @yrashk ,
> 
> My name is Veselina and I'm a PM at FlyCI. We're creating a case study around the usage of FlyCI in this repo. In relation to that, I'm wondering if you could share your experience with the product so far?
> 
> Thanks!

@radeva Overall, the experience is positive. However, I do see runners not coming up when requested relatively often.

**Comment by yrashk** [comment]
@radeva here's an example from minutes ago:

CleanShot 2024-01-23 at 07 51 08

**Comment by ligaz** [comment]
@yrashk As an immediate work-around can you please cancel this run and re-run it. This should mitigate the issue on your side.

**Pull request closed without merging**
