### PR TITLE
Problem: inability to quickly spin up familiar APIs (🚀 omni_rest 0.1.0)

### PR DESCRIPTION
**Pull request by yrashk**
Omnigres faces some adoption challenges as it proposes a different way to develop backends.

Solution: offer an automagic REST API provider
(PostgREST compatible)

---

# Bounty laundry list

This initial PR was the initial prototype to kick-start the project. Covering most of PostgREST functionality is a pretty big project, so we're creating a big collection of bounties!

- [x] ~~pg_yregress coverage of the basic functionality (tests are currently missing) ($100)~~
- [ ] Filtering expression sanitization ($250)
- [x] [Record insertion](https://docs.postgrest.org/en/v12/references/api/tables_views.html#insert), [updates](https://docs.postgrest.org/en/v12/references/api/tables_views.html#update) with [limited update](https://docs.postgrest.org/en/v12/references/api/tables_views.html#limited-update-delete)
[upserts](https://docs.postgrest.org/en/v12/references/api/tables_views.html#upsert#update) and [deletion](https://docs.postgrest.org/en/v12/references/api/tables_views.html#delete) ($250) -- limited insert/update, deletion is still not present
- [ ] [Pagination](https://docs.postgrest.org/en/v12/references/api/pagination_count.html) ($100)
- [x] [Horizontal filtering](https://docs.postgrest.org/en/v12/references/api/tables_views.html#horizontal-filtering) ($500)
- [ ] [Composite/array columns in vertical filtering](https://docs.postgrest.org/en/v12/references/api/tables_views.html#composite-array-columns) ($100)
- [ ] [Resource embedding](https://docs.postgrest.org/en/v12/references/api/resource_embedding.html) ($500)
- [ ] [OpenAPI support (preferably v3)](https://docs.postgrest.org/en/v12/references/api/openapi.html) ($500)
- [ ] Missing bits of [computed fields](https://docs.postgrest.org/en/v12/references/api/computed_fields.html#computed-fields) -- vertical filtering, ordering ($100)
- [ ] [Aggregated functions](https://docs.postgrest.org/en/v12/references/api/aggregate_functions.html) ($250)
- [ ] [RPC](https://docs.postgrest.org/en/v12/references/api/functions.html) _partially done_

(_the list to be extended and updated_)

If you want to take on a particular task, please mention it in the comments below so that others know you are working on it.

Please direct your PRs to the [omni_rest branch](https://github.com/yrashk/omnigres/tree/omni_rest) in @yrashk's fork so they can be included in this PR upon acceptance.

[Learn more about bounties](https://github.com/omnigres/omnigres/wiki/Bounties)

If you have any questions or thoughts, please comment below!

### CODE REVIEW

**Review by ebellani — COMMENTED** [review]
:+1:

**Comment by yrashk** [comment]
Horizontal filtering is being worked on by @diogob https://github.com/yrashk/omnigres/pull/4

**Comment by yrashk** [comment]
@diogob was doing another round of reviews and thinking about the potential for SQL injections in the `where` clause. I couldn't break through quoting immediately, which is good. But I wanted to bring to your attention that `omni_sql.execute` has an optional `parameters` attribute, which allows passing textual representations of parameters that can be referred to by their index (`$1,$2,...`)

Do you think it'd be sensible to try going this way to ensure we don't accidentally trip over this issue?

Merry Christmas! 🎄 🎅

**Comment by yrashk** [comment]
Rebased the branch off the current master to keep it up to date.

**Comment by diogob** [comment]
> @diogob was doing another round of reviews and thinking about the potential for SQL injections in the `where` clause. I couldn't break through quoting immediately, which is good. But I wanted to bring to your attention that `omni_sql.execute` has an optional `parameters` attribute, which allows passing textual representations of parameters that can be referred to by their index (`$1,$2,...`)
> 
> Do you think it'd be sensible to try going this way to ensure we don't accidentally trip over this issue?
> 
> Merry Christmas! 🎄 🎅

Good to know! I will use the parameters moving forward. On the horizontal filtering I was careful to always place parameter interpolation within a `format` call that will ensure proper quoting. But I prefer passing the parameters separately for clarity.

After our first release I can also circle back and refactor the horizontal filtering code so we have it all even.

Merry Christmas!

**Pull request merged**
