### PR TITLE
Problem: finding the correct version of OpenSSL

### PR DESCRIPTION
**Pull request by yrashk**
This is often a problem as target systems may have a wrong version, and discovery methods vary between systems and installation methods.

Solution: bring OpenSSL build to the configure stage if necessary

If a correct version of OpenSSL is not found, let's build it.

This also builds Perl to avoid depending on system Perl and Text::Template. On its own this seems a bit ridiculous, but considering we will be building PL/Perl, this would make more sense in the future.

This increases the configure time but (hopefully) makes builds more reliable.

### CODE REVIEW

**Comment by rmodpur** [comment]
This could help https://cmake.org/cmake/help/latest/module/FindOpenSSL.html

**Comment by yrashk** [comment]
> https://cmake.org/cmake/help/latest/module/FindOpenSSL.html

Finding the correct version only works if the target system has the correct version :) There are also systems where those installations don't have static versions of the library (which we use)

**Comment by rmodpur** [comment]
Yeah it won't install it for the user but will give an useful error and point out what kind of packages are missing from their system

**Comment by yrashk** [comment]
I've updated this PR to only build from scratch if a correct version can't be found.

**Pull request merged**
