### PR TITLE
chore(devenv): remove Nix Flake in favor of devenv-based environment

### PR DESCRIPTION
**Pull request by thenonameguy**
```
omnigres on  devenv via 🐳 orbstack via △ v3.26.4 via ❄️  impure (devenv-shell) took 1m59s
❯ pg
psql (15.4)
Type "help" for help.

omnigres=> \c
You are now connected to database "omnigres" as user "omnigres".
omnigres=> \pset pager off
Pager usage is off.
omnigres=> select name, default_version from pg_available_extensions;
             name             | default_version
------------------------------+-----------------
 refint                       | 1.0
 postgis                      | 3.3.3
 unaccent                     | 1.1
 btree_gin                    | 1.3
 ltree                        | 1.2
 tsm_system_rows              | 1.0
 datasketches                 | 1.6.0
 temporal_tables              | 1.2.0
 plr                          | 8.4.6
 jsonb_deep_sum               | 0.0.2
 plpgsql_check                | 2.4
 adminpack                    | 2.1
 dict_xsyn                    | 1.0
 pg_repack                    | 1.4.8
 address_standardizer         | 3.3.3
 xml2                         | 1.1
 hstore                       | 1.8
 pg_visibility                | 1.2
 tsearch_extras               | 1.0
 cube                         | 1.5
 postgis_tiger_geocoder       | 3.3.3
 seg                          | 1.4
 hll                          | 2.16
 intagg                       | 1.1
 tcn                          | 1.0
 isn                          | 1.2
 tsm_system_time              | 1.0
 pgroonga_database            | 3.0.8
 lo                           | 1.1
 pgrowlocks                   | 1.2
 pg_bigm                      | 1.2
 pgroonga                     | 3.0.8
 pg_hint_plan                 | 1.4
 sslinfo                      | 1.2
 topn                         | 2.5.0
 pgstattuple                  | 1.5
 autoinc                      | 1.0
 address_standardizer_data_us | 3.3.3
 postgis_topology             | 3.3.3
 postgis_raster               | 3.3.3
 pg_freespacemap              | 1.2
 pg_net                       | 0.7.1
 pg_relusage                  | 0.0.1
 file_fdw                     | 1.0
 pg_surgery                   | 1.0
 pg_buffercache               | 1.3
 dblink                       | 1.2
 pg_stat_statements           | 1.10
 insert_username              | 1.0
 repmgr                       | 5.4
 pg_prewarm                   | 1.2
 old_snapshot                 | 1.0
 pgtap                        | 1.2.0
 pg_ed25519                   | 0.2
 earthdistance                | 1.1
 uuid-ossp                    | 1.1
 intarray                     | 1.5
 periods                      | 1.2
 pg_trgm                      | 1.6
 dict_int                     | 1.0
 amcheck                      | 1.3
 vector                       | 0.5.0
 btree_gist                   | 1.7
 pageinspect                  | 1.11
 rum                          | 1.3
 moddatetime                  | 1.0
 pg_rational                  | 0.0.2
 pg_ivm                       | 1.5
 fuzzystrmatch                | 1.1
 pgautofailover               | 2.0
 pgrouting                    | 3.5.0
 pg_partman                   | 4.7.3
 pgcrypto                     | 1.3
 pg_similarity                | 1.0
 pg_cron                      | 1.5
 tablefunc                    | 1.0
 pg_walinspect                | 1.0
 postgres_fdw                 | 1.1
 smlar                        | 1.0
 bloom                        | 1.0
 pgjwt                        | 0.2.0
 citext                       | 1.6
 plpgsql                      | 1.0
 pgaudit                      | 1.7
(84 rows)
```

### CODE REVIEW

**Comment by yrashk** [comment]
Thank you so much for your contribution!

For my better understanding, what is the problem with flakes that devenv ultimately solves, esp. in this scenario? 

I am trying to understand if this contribution is intended to help "developing Omnigres" or "developing __with__ Omnigres"?

**Comment by yrashk** [comment]
Thank you for such a detailed explanation of your vision! I am going ahead and merging this; let's see how it will evolve over time :)

**Comment by yrashk** [comment]
It was removed due to lack of maintenance. Currently, Omnigres is in Nixpkgs. Maybe that can serve as a foundation for dev workflow?

**Comment by tomberek** [comment]
I should have checked there! duh, Thanks! Started to dig in. Running into some skip/todo failures in pg_yregress

**Comment by yrashk** [comment]
What kind of failures?

**Pull request merged**
